services:
  - type: web
    name: kitaab-backend
    env: node
    plan: free
    buildCommand: npm install --prefix Backend && npm install --prefix Frontend && npm run build --prefix Frontend
    startCommand: cd Backend && node app.js
    envVars:
      - key: NODE_ENV
        value: production
